on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to virtual machine
        run: |
          DEPLOY_TOKEN="{{ secrets.DEPLOY_TOKEN }}"
          REQUEST="$(curl -X POST -H "Content-Type: application/json" -d '{"deploy_key": ""}' https://oracle-3.jimmyliu.dev/deploy?repo_name=tej-online-judge)"
          echo $REQUEST
          if [[ "$REQUEST" == *"Error"* ]]; then exit 1; else exit 0; fi
