on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to virtual machine
        run: |
          if [[ "$(curl -X POST -H "Content-Type: application/json" -d '{"deploy_key": "{{ secrets.DEPLOY_KEY }}"}' https://oracle-3.jimmyliu.dev/deploy?repo_name=tej-online-judge)" == *"Error"* ]]; then exit 1; else exit 0; fi
